#!/usr/bin/env bun
/**
 * Reads SKILL.md YAML frontmatter descriptions and updates src/index.ts.
 * Called by scripts/update.sh after syncing skills from upstream.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const SKILLS_DIR = join(import.meta.dir, "..", "skills")
const INDEX_TS = join(import.meta.dir, "..", "src", "index.ts")

function parseDescription(frontmatter: string): string {
  const lines = frontmatter.split("\n")
  const idx = lines.findIndex((l) => /^description:/.test(l))
  if (idx === -1) return ""

  const line = lines[idx]
  const afterColon = line.replace(/^description:\s*/, "")

  // Block scalar (">" or "|") — collect indented continuation lines
  if (afterColon === ">" || afterColon === "|") {
    const parts: string[] = []
    for (let i = idx + 1; i < lines.length; i++) {
      if (!/^\s/.test(lines[i]) || lines[i].trim() === "") break
      parts.push(lines[i].trim())
    }
    return parts.join(" ").replace(/\s+/g, " ")
  }

  return afterColon.trim()
}

function extractDescription(mdPath: string): string {
  const content = readFileSync(mdPath, "utf-8")
  const m = content.match(/^---\n([\s\S]*?)\n---/)
  if (!m) throw new Error(`No frontmatter in ${mdPath}`)
  return parseDescription(m[1])
}

function esc(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
}

const entries = readdirSync(SKILLS_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort()
  .map((name) => {
    const desc = extractDescription(join(SKILLS_DIR, name, "SKILL.md"))
    const escaped = esc(desc)
    // Long descriptions get line-broken for readability
    if (escaped.length > 100) {
      return `        {\n          name: "${name}",\n          description:\n            "${escaped}",\n          dir: "skills/${name}",\n        }`
    }
    return `        { name: "${name}", description: "${escaped}", dir: "skills/${name}" }`
  })

const indexTs = readFileSync(INDEX_TS, "utf-8")
const startMarker = "// ═══ SKILLS"
const endMarker = "// ═══ END SKILLS ═══"

const startIdx = indexTs.indexOf(startMarker)
const endIdx = indexTs.indexOf(endMarker)
if (startIdx === -1 || endIdx === -1) {
  console.error("Guard comments not found in src/index.ts")
  process.exit(1)
}

// Replace everything between the guard comments
const newBlock = `      // ═══ SKILLS — generated by scripts/update.sh — do not edit manually ═══
      skills: [
${entries.join(",\n")},
      ],
      // ═══ END SKILLS ═══`

const result =
  indexTs.substring(0, startIdx) +
  newBlock +
  indexTs.substring(endIdx + endMarker.length)

writeFileSync(INDEX_TS, result, "utf-8")
console.log(`✓ Updated ${entries.length} skill descriptions in src/index.ts`)
