#!/usr/bin/env bun
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface SkillSource {
  name: string;
}

interface SourcesFile {
  skills: SkillSource[];
}

interface SkillEntry {
  name: string;
  description: string;
  dir: string;
}

const ROOT = join(import.meta.dir, "..");
const SKILLS_DIR = join(ROOT, "skills");
const SKILLS_TS = join(ROOT, "src", "skills.ts");
const SOURCES_PATH = join(ROOT, "skills.sources.json");

function parseDescription(frontmatter: string): string {
  const lines = frontmatter.split("\n");
  const index = lines.findIndex((line) => /^description:/.test(line));
  if (index === -1) return "";
  const afterColon = lines[index].replace(/^description:\s*/, "");
  if (afterColon === ">" || afterColon === "|") {
    const parts: string[] = [];
    for (let current = index + 1; current < lines.length; current++) {
      const line = lines[current];
      if (!/^\s/.test(line)) break;
      parts.push(line.trim());
    }
    return parts.join(" ").replace(/\s+/g, " ").trim();
  }
  return stripOuterQuotes(afterColon.trim());
}

function stripOuterQuotes(value: string): string {
  if (value.length < 2) return value;
  const first = value[0];
  const last = value[value.length - 1];
  return (first === `"` || first === "'") && first === last
    ? value.slice(1, -1)
    : value;
}

function extractDescription(path: string): string {
  const content = readFileSync(path, "utf-8");
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) throw new Error(`No frontmatter in ${path}`);
  return parseDescription(match[1]);
}

function renderSkillEntry(entry: SkillEntry): string {
  return `  {\n    name: ${JSON.stringify(entry.name)},\n    description:\n      ${JSON.stringify(entry.description)},\n    dir: ${JSON.stringify(entry.dir)},\n  }`;
}

function replaceBetweenMarkers(
  content: string,
  startMarker: string,
  endMarker: string,
  replacement: string,
): string {
  const start = content.indexOf(startMarker);
  const end = content.indexOf(endMarker);
  if (start === -1 || end === -1 || end <= start)
    throw new Error(`Guard comments not found: ${startMarker} / ${endMarker}`);
  return (
    content.slice(0, start) +
    replacement +
    content.slice(end + endMarker.length)
  );
}

const sources = JSON.parse(readFileSync(SOURCES_PATH, "utf-8")) as SourcesFile;
const entries = sources.skills.map((source) => ({
  name: source.name,
  description: extractDescription(join(SKILLS_DIR, source.name, "SKILL.md")),
  dir: `skills/${source.name}`,
}));
const startMarker = "// === SKILLS:";
const endMarker = "// === END SKILLS ===";
const replacement = `${startMarker} generated by scripts/sync-descriptions.ts; do not edit manually ===\nexport const SKILL_ENTRIES: PluginSkill[] = [\n${entries.map(renderSkillEntry).join(",\n")},\n]\n${endMarker}`;
const current = readFileSync(SKILLS_TS, "utf-8");
writeFileSync(
  SKILLS_TS,
  replaceBetweenMarkers(current, startMarker, endMarker, replacement),
  "utf-8",
);
console.log(`Updated ${entries.length} skill descriptions in src/skills.ts`);
